services:
  - type: worker
    name: poketon-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: TSSLG
        sync: false
    plan: free

